services:
  db:
    image: postgres:15-alpine
    container_name: footy_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: footy_stats_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: footy_server
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password123@db:5432/footy_stats_db?schema=public
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: footy_client
    depends_on:
      - server
    ports:
      - "5185:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_PORT=5173

volumes:
  postgres_data:
